import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ApplicationFormData, generateApplicationPdf } from '../lib/pdf';
import { buildInvitationInfo } from '../lib/invite';
import {
  canSharePdfFile,
  shareFileWithNativeApp,
  downloadFile,
  copyTextToClipboard,
  getWebmailLinks,
  buildRecipientPayloads,
  isNarrowMobileBrowser,
  shareInvitation,
} from '../lib/share';
import { PollingStation } from '../data/missions';
import { useScript } from '../lib/script';
import { ElectionNoticeLink } from './ElectionNoticeLink';
import { MissionInquiryLink } from './MissionInquiryLink';
import { CountryFlag } from './CountryFlag';
/**
 * Creates a PDF from the wizard's in-memory application data and prepares handoff helpers.
 * Download, mail links, clipboard writes, and native sharing leave the final attachment and
 * sending decision to the user; this component does not deliver an application itself.
 */


interface StepExportAndSubmitProps {
  formData: ApplicationFormData;
  station: PollingStation;
  countryName: string;
  countryNameCyr: string;
  countryCode?: string;
  isWetInkSignature: boolean;
  onBack: () => void;
  onReset: () => void;
}

export const StepExportAndSubmit: React.FC<StepExportAndSubmitProps> = ({
  formData,
  station,
  countryName,
  countryNameCyr,
  countryCode,
  isWetInkSignature,
  onBack,
  onReset,
}) => {
  const { script, t } = useScript();
  const selectedCountryName = script === 'cyrillic' ? countryNameCyr : countryName;
  const selectedEmbassy = script === 'cyrillic' ? station.embassyCyr : station.embassy;

  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [pdfBytes, setPdfBytes] = useState<Uint8Array | null>(null);
  const pdfBytesRef = useRef<Uint8Array | null>(null);
  const pdfGenerationRef = useRef<Promise<Uint8Array> | null>(null);
  const [pdfError, setPdfError] = useState<string | null>(null);
  const [hasDownloaded, setHasDownloaded] = useState<boolean>(false);
  const [copiedEmail, setCopiedEmail] = useState<boolean>(false);
  const [copiedBody, setCopiedBody] = useState<boolean>(false);
  const [shareError, setShareError] = useState<string | null>(null);
  const [invitationStatus, setInvitationStatus] = useState<{
    success: boolean;
    message: string;
  } | null>(null);
  const [isSharingInvitation, setIsSharingInvitation] = useState<boolean>(false);
  const mobileSharingAvailable = !isWetInkSignature && canSharePdfFile();
  const hideProviderLinks = isNarrowMobileBrowser();
  const desiredLocation = formData.desiredLocation?.trim() ?? '';

  const subject = 'Пријава за гласање из иностранства — избори 2026.';
  const isIdDocumentEmbedded = Boolean(formData.idDocumentDataUrl);
  const idDocumentSentence = isIdDocumentEmbedded
    ? 'Копија идентификационог документа уграђена је у PDF.'
    : 'Уз пријаву достављам и копију идентификационог документа.';
  const messageBody = isWetInkSignature
    ? `Поштовани,

Након штампања и својеручног потписивања, у прилогу достављам скенирану или фотографисану пријаву за гласање у иностранству за изборе 2026. године. ${idDocumentSentence}

Држава боравка: ${countryNameCyr}
Дипломатско представништво: ${station.embassyCyr}

Молим за потврду пријема захтева.`
    : `Поштовани,

У прилогу достављам попуњен и потписан Захтев за упис у бирачки списак податка да ћу гласати у иностранству на предстојећим изборима 2026. године. ${idDocumentSentence}

Држава боравка: ${countryNameCyr}
Дипломатско представништво: ${station.embassyCyr}

Молим за потврду пријема захтева.`;

  // Recipient text reflects the selected approval status; it does not prove a mission will
  // accept the message.
  const { dispatchInfo, webShareInfo, manualText } = buildRecipientPayloads({
    toEmail: station.email,
    electionContactApproval: station.electionContactApproval,
    isIdDocumentEmbedded,
    isWetInkSignature,
    subject,
    body: messageBody,
    fullName: formData.fullName,
  });

  const webmailLinks = getWebmailLinks(dispatchInfo);

  // Keep one generated byte sequence and one in-flight promise per mounted export step. This
  // avoids repeated PDF work and ensures download/share use the same locally created document.
  const ensurePdf = useCallback((): Promise<Uint8Array> => {
    if (pdfBytesRef.current) return Promise.resolve(pdfBytesRef.current);
    if (pdfGenerationRef.current) return pdfGenerationRef.current;

    setIsGenerating(true);
    setPdfError(null);
    const generation = generateApplicationPdf(formData)
      .then((generated) => {
        pdfBytesRef.current = generated;
        setPdfBytes(generated);
        return generated;
      })
      .catch((err) => {
        setPdfError(`${t('Greška pri generisanju PDF dokumenta:')} ${String(err)}`);
        throw err;
      })
      .finally(() => {
        pdfGenerationRef.current = null;
        setIsGenerating(false);
      });

    pdfGenerationRef.current = generation;
    return generation;
  }, [formData, t]);

  // A digital signature can be prepared immediately; wet ink must wait for the user's manual
  // print-and-sign workflow.
  useEffect(() => {
    if (!isWetInkSignature) {
      void ensurePdf().catch(() => undefined);
    }
  }, [ensurePdf, isWetInkSignature]);

  const handleDownload = async () => {
    try {
      const bytes = await ensurePdf();
      downloadFile(bytes, 'Zahtev-za-glasanje-2026.pdf');
      setHasDownloaded(true);
    } catch {
      // The inline PDF error remains visible and this button allows another attempt.
    }
  };

  // Native share receives a file chosen by the user in the next UI. Platform APIs cannot make
  // this an automatic submission or guarantee a recipient/attachment in the selected app.
  const handleNativeShare = () => {
    if (!pdfBytes) return;

    setShareError(null);
    const file = new File([pdfBytes.buffer as ArrayBuffer], 'Zahtev-za-glasanje-2026.pdf', {
      type: 'application/pdf',
    });

    void shareFileWithNativeApp(file, webShareInfo, script).then((result) => {
      if (!result.success && result.error) {
        setShareError(result.error);
      }
    });
  };

  const handleCopyEmail = async () => {
    const success = await copyTextToClipboard(station.email);
    if (success) {
      setCopiedEmail(true);
      setTimeout(() => setCopiedEmail(false), 3000);
    }
  };

  const handleCopyBody = async () => {
    const success = await copyTextToClipboard(manualText);
    if (success) {
      setCopiedBody(true);
      setTimeout(() => setCopiedBody(false), 3000);
    }
  };

  // This shares only a location-prefilled invitation link, never the current applicant's form data.
  const handleInvitationShare = () => {
    const desiredLocation = formData.desiredLocation?.trim();
    if (!desiredLocation || typeof window === 'undefined') return;

    setInvitationStatus(null);
    setIsSharingInvitation(true);
    const invitation = buildInvitationInfo(
      window.location.origin,
      window.location.pathname,
      desiredLocation,
      script,
    );

    void shareInvitation(invitation, script).then((result) => {
      setIsSharingInvitation(false);
      setInvitationStatus(
        result.success
          ? {
              success: true,
              message: result.method === 'native'
                ? t('Poziv je podeljen.')
                : t('Poziv i veza su kopirani u privremenu memoriju.'),
            }
          : { success: false, message: result.error },
      );
    });
  };

  const downloadLabel = isWetInkSignature
    ? t('🖨️ Preuzmi PDF za štampu i potpis →')
    : t('📥 Preuzmi potpisan PDF formular →');

  return (
    <div className="card">
      <h2 className="card-title">{t('Korak 5: Preuzimanje i predaja prijave')}</h2>
      <p className="card-subtitle">
        {t('Preuzmite PDF, zatim ga sami priložite u poruku ili ga prenesite u izabranu aplikaciju. Ova stranica samo priprema PDF i ne obavlja predaju.')}
      </p>

      {station.electionContactApproval === 'unconfirmed' && (
        <div
          role="alert"
          style={{
            background: 'var(--color-error-bg)',
            border: '2px solid var(--color-danger)',
            borderRadius: 'var(--radius-md)',
            color: 'var(--color-danger)',
            fontWeight: 700,
            marginBottom: '1.5rem',
            padding: '1rem',
          }}
        >
          {t('Adresa za izbore nije potvrđena. Ovo je opšti kontakt misije, a ne potvrđeno elektronsko sanduče za upis u birački spisak. Možete sačekati potvrđeno zvanično obaveštenje ili sami proveriti sajt misije u odeljku za kontakt na dnu stranice.')}
          <ElectionNoticeLink notice={station.electionNotice} status={station.electionNoticeStatus} />
        </div>
      )}

      <div
        style={{
          background: '#f8fafc',
          border: '1px solid #cbd5e1',
          borderRadius: 'var(--radius-md)',
          padding: '1rem',
          marginBottom: '1.5rem',
        }}
      >
        <div style={{ fontWeight: 700, color: 'var(--color-primary)', marginBottom: '0.5rem' }}>
          {t('📋 Sažetak prijave')}
        </div>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
            gap: '0.5rem',
            fontSize: '0.85rem',
          }}
        >
          <div>
            <strong>{t('Država:')}</strong>{' '}
            <span className="country-label">
              <CountryFlag countryCode={countryCode} />
              <span>{selectedCountryName}</span>
            </span>
          </div>
          <div><strong>{t('Predstavništvo:')}</strong> {selectedEmbassy}</div>
          <div>
            <strong>{t('Prilog pasoša:')}</strong>{' '}
            {formData.idDocumentDataUrl
              ? t('Ugrađen kao strana 2 u PDF')
              : t('Nije učitan; priložite ga zasebno')}
          </div>
        </div>
      </div>

      {mobileSharingAvailable && (
        <section
          aria-labelledby="mobile-handoff-title"
          style={{
            border: '1px solid var(--color-border)',
            borderRadius: 'var(--radius-md)',
            padding: '1rem',
            marginBottom: '1.5rem',
          }}
        >
          <h3 id="mobile-handoff-title" style={{ marginTop: 0 }}>{t('Na telefonu: podeli PDF (Web Share)')}</h3>
          <p>
            {t('Otvorite deljenje i izaberite ')}Gmail, Apple Mail, Outlook {t('ili ')}Yahoo Mail{t(' da prenesete PDF. U izabranoj aplikaciji ručno unesite adresu primaoca prema uputstvu u tekstu poruke, pa uklonite to privremeno uputstvo pre slanja.')}
          </p>
          <button
            type="button"
            onClick={handleNativeShare}
            disabled={isGenerating || !pdfBytes}
            className="btn btn-primary btn-lg btn-block"
          >
            {pdfBytes
              ? t('✉️➕📄 Podeli PDF u svoju aplikaciju za e-poštu →')
              : isGenerating || !pdfError
                ? t('⏳ Pripremanje PDF-a...')
                : t('PDF nije pripremljen')}
          </button>
          <p className="form-hint" style={{ textAlign: 'center' }}>
            {t('Deljenje prenosi PDF i isti naslov i tekst poruke, ali ne unosi primaoca, ne dodaje adresu i ne šalje poruku.')}
          </p>
          {pdfError && (
            <div className="alert alert-warning" style={{ marginTop: '0.5rem' }}>
              {pdfError}
            </div>
          )}
          {shareError && (
            <div className="alert alert-warning" style={{ marginTop: '0.5rem' }}>
              {shareError}
            </div>
          )}
        </section>
      )}
      {desiredLocation && (
        <section
          aria-labelledby="invitation-title"
          style={{
            border: '1px solid var(--color-border)',
            borderRadius: 'var(--radius-md)',
            padding: '1rem',
            marginBottom: '1.5rem',
          }}
        >
          <h3 id="invitation-title" style={{ marginTop: 0 }}>
            {t('Podelite sa prijateljima')}
          </h3>
          <p>
            {t('Pošaljite drugima vezu koja unapred popunjava njihovo željeno mesto glasanja: ')}
            <strong>{desiredLocation}</strong>.
          </p>
          <button
            type="button"
            onClick={handleInvitationShare}
            disabled={isSharingInvitation}
            className="btn btn-outline"
          >
            {isSharingInvitation ? t('Deljenje poziva...') : t('Podeli poziv i vezu')}
          </button>
          {invitationStatus && (
            <div
              role={invitationStatus.success ? 'status' : 'alert'}
              style={{
                color: invitationStatus.success ? 'var(--color-success)' : 'var(--color-danger)',
                fontWeight: 600,
                marginTop: '0.75rem',
              }}
            >
              {invitationStatus.message}
            </div>
          )}
        </section>
      )}


      {isWetInkSignature && (
        <div className="alert alert-warning" style={{ marginBottom: '1.5rem' }}>
          {t('Potreban je svojeručni potpis. Ovaj PDF nije potpisan za slanje: odštampajte ga, potpišite, pa napravite sken ili jasnu fotografiju. U poruku se ručno prilaže tek skenirani/fotografisani potpisani obrazac.')}
        </div>
      )}


      <section
        aria-labelledby="desktop-handoff-title"
        style={{
          border: '1px solid var(--color-border)',
          borderRadius: 'var(--radius-md)',
          padding: '1rem',
          marginBottom: '1.5rem',
        }}
      >
        <h3 id="desktop-handoff-title" style={{ marginTop: 0 }}>{t('Ručno: preuzimanje i prilaganje PDF-a')}</h3>
        <p><strong>1.</strong> {t('Preuzmite PDF na uređaj.')}</p>
        <button
          type="button"
          onClick={handleDownload}
          disabled={isGenerating}
          className="btn btn-secondary btn-lg btn-block"
        >
          {isGenerating ? t('⏳ Generisanje PDF-a...') : downloadLabel}
        </button>
        {!mobileSharingAvailable && pdfError && (
          <div className="alert alert-warning" style={{ marginTop: '0.5rem' }}>
            {pdfError}
          </div>
        )}
        {hasDownloaded && (
          <div
            style={{
              fontSize: '0.85rem',
              color: 'var(--color-success)',
              fontWeight: 600,
              textAlign: 'center',
              marginTop: '0.5rem',
            }}
          >
            {isWetInkSignature
              ? t('✓ PDF je preuzet. Slede štampanje, potpis i skeniranje ili fotografisanje.')
              : t('✓ PDF je preuzet na vaš uređaj.')}
          </div>
        )}

        <div style={{ marginTop: '1.25rem', paddingTop: '1rem', borderTop: '1px solid var(--color-border)' }}>
          <p><strong>2.</strong> {t('Otvorite pripremljenu poruku, ručno priložite PDF i sami je pošaljite.')}</p>
          <a href={webmailLinks.mailto} className="btn btn-primary btn-lg btn-block">
            {t('✉️ Otvori pripremljenu e-poštu →')}
          </a>
          <p className="form-hint">
            {t('Veza otvara podrazumevani program za e-poštu sa pripremljenim primaocem, naslovom i tekstom, ali ne može da priloži PDF niti da pošalje poruku. Ako tekst na početku traži dodatni prilog, priložite ga, pa uklonite to privremeno uputstvo pre slanja.')}
          </p>

          {!hideProviderLinks && (
            <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginTop: '0.75rem' }}>
              <a href={webmailLinks.gmail} target="_blank" rel="noopener noreferrer" className="btn btn-sm btn-secondary">
                {t('Nastavi u ')}Gmail{t('-u ↗')}
              </a>
              <a href={webmailLinks.outlook} target="_blank" rel="noopener noreferrer" className="btn btn-sm btn-secondary">
                {t('Nastavi u ')}Outlook{t('-u ↗')}
              </a>
              <a href={webmailLinks.yahoo} target="_blank" rel="noopener noreferrer" className="btn btn-sm btn-secondary">
                {t('Nastavi u ')}Yahoo Mail{t('-u ↗')}
              </a>
            </div>
          )}

          <div style={{ marginTop: '1rem' }}>
            <p className="form-hint">
              {t('Potpuno ručna alternativa: ako ne možete da otvorite pripremljenu poruku, kopirajte adresu, naslov i tekst u svoju aplikaciju za e-poštu. Kopirani tekst počinje privremenim uputstvima: postupite po njima, pa ih uklonite pre slanja.')}
            </p>
            <button type="button" onClick={handleCopyBody} className="btn btn-sm btn-outline">
              {copiedBody
                ? t('✓ Adresa, naslov i tekst su kopirani')
                : t('📝 Kopiraj adresu, naslov i tekst poruke')}
            </button>
          </div>
        </div>

        <div style={{ marginTop: '1.25rem', paddingTop: '1rem', borderTop: '1px solid var(--color-border)' }}>
          <p><strong>3.</strong> {t('Ručno priložite i proverite pre predaje.')}</p>
          <ul className="checklist">
            <li className="checklist-item">
              <span className="checklist-icon">📎</span>
              <span>
                <strong>{t('Priložite PDF:')}</strong>{' '}
                {isWetInkSignature
                  ? t('priložite skenirani ili fotografisani potpisani obrazac, ne nepotpisani PDF za štampu.')
                  : t('priložite preuzeti PDF formular.')}
              </span>
            </li>
            <li className="checklist-item">
              <span className="checklist-icon">📸</span>
              <span>
                <strong>{t('Kopija pasoša / lične karte:')}</strong>{' '}
                {isIdDocumentEmbedded
                  ? t('već je ugrađena kao strana 2 PDF-a.')
                  : t('ručno priložite sliku prve strane srpskog pasoša ili lične karte.')}
              </span>
            </li>
            <li className="checklist-item">
              <span className="checklist-icon">✓</span>
              <span>{t('Proverite: adresu primaoca, naslov, priloge i čitljivost potpisa pre nego što sami predate poruku.')}</span>
            </li>
          </ul>
        </div>
      </section>
      <div className="hub-card" style={{ padding: '1.25rem', borderRadius: 'var(--radius-lg)', marginBottom: '1.5rem' }}>
        <div style={{ fontWeight: 700, color: 'var(--color-primary)', fontSize: '1.05rem' }}>
          {t('✉️ Javno objavljeni kontakt misije/konzulata')}
        </div>
        <p
          style={{
            color: station.electionContactApproval === 'unconfirmed'
              ? 'var(--color-danger)'
              : 'var(--color-success)',
            fontSize: '0.9rem',
            fontWeight: 700,
            margin: '0.5rem 0',
          }}
        >
          {station.electionContactApproval !== 'unconfirmed'
            ? t('✓ Potvrđena adresa za izbore 2026.')
            : t('Nije potvrđena adresa za izbore — ovo je samo opšti kontakt misije.')}
        </p>
        <ElectionNoticeLink notice={station.electionNotice} status={station.electionNoticeStatus} showMissing={station.electionContactApproval !== 'unconfirmed'} />
        <MissionInquiryLink station={station} countryName={selectedCountryName} />
        {station.electionContactApproval === 'unconfirmed' && (
          <p style={{ fontSize: '0.85rem', color: 'var(--color-text-muted)', margin: '0.25rem 0 0.5rem' }}>
            {t('Možete sačekati potvrđeno zvanično obaveštenje ili sami proveriti ovaj sajt misije pre predaje.')}
          </p>
        )}
        <div className="hub-email-box">
          <span className="hub-email-text">{station.email}</span>
          <button
            type="button"
            onClick={handleCopyEmail}
            className="btn btn-sm btn-outline"
          >
            {copiedEmail ? t('✓ Adresa je kopirana') : t('📋 Kopiraj adresu primaoca')}
          </button>
        </div>
        <a
          href={station.website}
          target="_blank"
          rel="noopener noreferrer"
          className="btn btn-sm btn-outline"
          style={{ marginTop: '0.75rem' }}
        >
          {t('🌐 Zvanični sajt misije ↗')}
        </a>
      </div>

      <aside className="mission-card" aria-labelledby="registry-reminder-title" style={{ marginBottom: '1.5rem' }}>
        <h3 id="registry-reminder-title" className="mission-title">
          {t('Ne zaboravite proveru biračkog spiska')}
        </h3>
        <p>{t('Ako već niste, proverite da li ste upisani u jedinstveni birački spisak.')}</p>
        <a href="https://upit.birackispisak.gov.rs/" target="_blank" rel="noopener noreferrer" className="btn btn-sm btn-outline">
          {t('Proverite upis u birački spisak')} ↗
        </a>
        <p className="form-hint">
          {t('Ako niste upisani, od misije zatražite i obrazac za upis u birački spisak i podnesite ga zajedno sa zahtevom za glasanje u inostranstvu. Ovaj alat priprema samo zahtev za glasanje u inostranstvu.')}
        </p>
      </aside>

      <div className="btn-row">
        <button type="button" onClick={onBack} className="btn btn-secondary">
          {t('← Nazad na pregled podataka')}
        </button>
        <button
          type="button"
          onClick={onReset}
          className="btn btn-outline"
          style={{ color: 'var(--color-text-muted)' }}
        >
          {t('Započni novu prijavu')}
        </button>
      </div>
    </div>
  );
};
